######################################
#
# BUSCO summary figure
# @author Mathieu Seppey <mathieu.seppey@unige.ch>
# @version 2.0
# @since BUSCO 2.0
# 
# Copyright (C) 2016 E. Zdobnov lab
# 
# BUSCO is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. See <http://www.gnu.org/licenses/>
#  
# BUSCO is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("/mnt/dessertlocal/projects/transcriptome_assembly/review/evaluation/busco/eco/plot/","busco_figure.pdf",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('eco_spades', 'eco_spades', 'eco_spades', 'eco_spades', 'eco_trans-abyss', 'eco_trans-abyss', 'eco_trans-abyss', 'eco_trans-abyss', 'eco_shannon', 'eco_shannon', 'eco_shannon', 'eco_shannon', 'eco_trinity', 'eco_trinity', 'eco_trinity', 'eco_trinity', 'eco_idba-tran', 'eco_idba-tran', 'eco_idba-tran', 'eco_idba-tran', 'eco_oases', 'eco_oases', 'eco_oases', 'eco_oases', 'eco_binpacker', 'eco_binpacker', 'eco_binpacker', 'eco_binpacker', 'eco_soap-trans-default', 'eco_soap-trans-default', 'eco_soap-trans-default', 'eco_soap-trans-default', 'eco_bridger', 'eco_bridger', 'eco_bridger', 'eco_bridger', 'eco_rna-spades', 'eco_rna-spades', 'eco_rna-spades', 'eco_rna-spades')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(42.5, 0.0, 35.5, 22.0, 29.3, 8.7, 40.2, 21.8, 33.4, 2.4, 38.8, 25.4, 35.7, 0.6, 39.3, 24.4, 37.9, 0.0, 37.0, 25.1, 17.4, 20.9, 39.7, 22.0, 6.1, 0.3, 2.6, 91.0, 40.5, 0.0, 36.7, 22.8, 36.0, 0.5, 39.2, 24.3, 32.5, 0.1, 43.1, 24.3)
my_values <- c(332, 0, 277, 172, 229, 68, 314, 170, 261, 19, 303, 198, 279, 5, 307, 190, 296, 0, 289, 196, 136, 163, 310, 172, 48, 2, 20, 711, 316, 0, 287, 178, 281, 4, 306, 190, 254, 1, 337, 189)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
