######################################
#
# BUSCO summary figure
# @author Mathieu Seppey <mathieu.seppey@unige.ch>
# @version 2.0
# @since BUSCO 2.0
# 
# Copyright (C) 2016 E. Zdobnov lab
# 
# BUSCO is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. See <http://www.gnu.org/licenses/>
#  
# BUSCO is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("/mnt/dessertlocal/projects/transcriptome_assembly/review/evaluation/busco/ebov_hsa_23h/plot/","busco_figure.pdf",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('ebov_hsa_23h_trans-abyss', 'ebov_hsa_23h_trans-abyss', 'ebov_hsa_23h_trans-abyss', 'ebov_hsa_23h_trans-abyss', 'ebov_hsa_23h_rna-spades', 'ebov_hsa_23h_rna-spades', 'ebov_hsa_23h_rna-spades', 'ebov_hsa_23h_rna-spades', 'ebov_hsa_23h_oases', 'ebov_hsa_23h_oases', 'ebov_hsa_23h_oases', 'ebov_hsa_23h_oases', 'ebov_hsa_23h_binpacker', 'ebov_hsa_23h_binpacker', 'ebov_hsa_23h_binpacker', 'ebov_hsa_23h_binpacker', 'ebov_hsa_23h_soap-trans-default', 'ebov_hsa_23h_soap-trans-default', 'ebov_hsa_23h_soap-trans-default', 'ebov_hsa_23h_soap-trans-default', 'ebov_hsa_23h_bridger', 'ebov_hsa_23h_bridger', 'ebov_hsa_23h_bridger', 'ebov_hsa_23h_bridger', 'ebov_hsa_23h_shannon', 'ebov_hsa_23h_shannon', 'ebov_hsa_23h_shannon', 'ebov_hsa_23h_shannon', 'ebov_hsa_23h_spades', 'ebov_hsa_23h_spades', 'ebov_hsa_23h_spades', 'ebov_hsa_23h_spades', 'ebov_hsa_23h_trinity', 'ebov_hsa_23h_trinity', 'ebov_hsa_23h_trinity', 'ebov_hsa_23h_trinity', 'ebov_hsa_23h_idba-tran', 'ebov_hsa_23h_idba-tran', 'ebov_hsa_23h_idba-tran', 'ebov_hsa_23h_idba-tran')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(33.4, 29.7, 5.3, 31.6, 48.8, 6.2, 12.8, 32.2, 15.2, 46.7, 5.6, 32.5, 14.3, 13.1, 1.7, 70.9, 52.3, 3.2, 11.5, 33.0, 41.7, 19.4, 6.9, 32.0, 23.0, 23.0, 9.3, 44.7, 59.6, 0.3, 8.6, 31.5, 34.4, 28.3, 5.9, 31.4, 32.8, 0.1, 28.0, 39.1)
my_values <- c(2068, 1839, 331, 1954, 3019, 386, 795, 1992, 939, 2893, 346, 2014, 883, 812, 105, 4392, 3238, 197, 715, 2042, 2581, 1203, 430, 1978, 1426, 1426, 576, 2764, 3693, 17, 530, 1952, 2130, 1755, 363, 1944, 2034, 8, 1731, 2419)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
